# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pedroalves/Midiacom/cpp/vrecog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pedroalves/Midiacom/cpp/vrecog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pedroalves/Midiacom/cpp/vrecog/CMakeFiles /home/pedroalves/Midiacom/cpp/vrecog/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pedroalves/Midiacom/cpp/vrecog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vrecog

# Build rule for target.
vrecog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vrecog
.PHONY : vrecog

# fast build rule for target.
vrecog/fast:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/build
.PHONY : vrecog/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/userKeyElement.o: src/userKeyElement.cpp.o

.PHONY : src/userKeyElement.o

# target to build an object file
src/userKeyElement.cpp.o:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/userKeyElement.cpp.o
.PHONY : src/userKeyElement.cpp.o

src/userKeyElement.i: src/userKeyElement.cpp.i

.PHONY : src/userKeyElement.i

# target to preprocess a source file
src/userKeyElement.cpp.i:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/userKeyElement.cpp.i
.PHONY : src/userKeyElement.cpp.i

src/userKeyElement.s: src/userKeyElement.cpp.s

.PHONY : src/userKeyElement.s

# target to generate assembly for a file
src/userKeyElement.cpp.s:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/userKeyElement.cpp.s
.PHONY : src/userKeyElement.cpp.s

src/voiceRecognition.o: src/voiceRecognition.cpp.o

.PHONY : src/voiceRecognition.o

# target to build an object file
src/voiceRecognition.cpp.o:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/voiceRecognition.cpp.o
.PHONY : src/voiceRecognition.cpp.o

src/voiceRecognition.i: src/voiceRecognition.cpp.i

.PHONY : src/voiceRecognition.i

# target to preprocess a source file
src/voiceRecognition.cpp.i:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/voiceRecognition.cpp.i
.PHONY : src/voiceRecognition.cpp.i

src/voiceRecognition.s: src/voiceRecognition.cpp.s

.PHONY : src/voiceRecognition.s

# target to generate assembly for a file
src/voiceRecognition.cpp.s:
	$(MAKE) -f CMakeFiles/vrecog.dir/build.make CMakeFiles/vrecog.dir/src/voiceRecognition.cpp.s
.PHONY : src/voiceRecognition.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vrecog"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/userKeyElement.o"
	@echo "... src/userKeyElement.i"
	@echo "... src/userKeyElement.s"
	@echo "... src/voiceRecognition.o"
	@echo "... src/voiceRecognition.i"
	@echo "... src/voiceRecognition.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

